In [1]:
import tensorflow as tf
import pandas as pd
from sklearn import preprocessing

# Fetching and Preprocessing Data

In [2]:
trainData = pd.read_csv('titanic/train.csv')
testData = pd.read_csv('titanic/test.csv')

In [3]:
trainData.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
testData.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [5]:
def clean(data):
    data = data.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)
    data['Embarked'] = data['Embarked'].fillna('U')
    data['Age'] = data['Age'].fillna(data["Age"].mean())
    data['SibSp'] = data['SibSp'].fillna(data["SibSp"].mean())
    data['Parch'] = data['Parch'].fillna(data["Parch"].mean())
    data['Fare'] = data['Fare'].fillna(data["Fare"].mean())
    
    le = preprocessing.LabelEncoder()

    for col in ['Sex', 'Embarked']:
        data[col] = le.fit_transform(data[col])
        
    return data

In [6]:
trainDataClean = clean(trainData)
testDataClean = clean(testData)

In [7]:
trainDataClean.head(11)

    Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0          0       3    1  22.000000      1      0   7.2500         2
1          1       1    0  38.000000      1      0  71.2833         0
2          1       3    0  26.000000      0      0   7.9250         2
3          1       1    0  35.000000      1      0  53.1000         2
4          0       3    1  35.000000      0      0   8.0500         2
5          0       3    1  29.699118      0      0   8.4583         1
6          0       1    1  54.000000      0      0  51.8625         2
7          0       3    1   2.000000      3      1  21.0750         2
8          1       3    0  27.000000      0      2  11.1333         2
9          1       2    0  14.000000      1      0  30.0708         0
10         1       3    0   4.000000      1      1  16.7000         2

In [8]:
testDataClean.head(5)

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    1  34.5      0      0   7.8292         1
1       3    0  47.0      1      0   7.0000         2
2       2    1  62.0      0      0   9.6875         1
3       3    1  27.0      0      0   8.6625         2
4       3    0  22.0      1      1  12.2875         2

In [9]:
temp1 = trainDataClean[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']].to_numpy()
temp2 = trainDataClean['Survived'].to_numpy()

trainX = temp1[0:600]
valX = temp1[600:]

trainY = temp2[0:600]
valY = temp2[600:]

testX = testDataClean[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Embarked']].to_numpy()

In [10]:
print('TrainX Shape: {}'.format(trainX.shape))
print('ValX Shape: {}'.format(valX.shape))
print('TestX Shape: {}'.format(testX.shape))

print('TrainY Shape: {}'.format(trainY.shape))
print('ValY Shape: {}'.format(valY.shape))

TrainX Shape: (600, 7)
ValX Shape: (291, 7)
TestX Shape: (418, 7)
TrainY Shape: (600,)
ValY Shape: (291,)

# Building and Training Model

In [11]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(10, activation = 'relu'))
model.add(tf.keras.layers.Dense(1, activation = 'sigmoid'))

model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [12]:
model.fit(trainX, trainY, validation_data = (valX, valY), epochs = 150)

Epoch 1/150
19/19 [==============================] - 1s 15ms/step - loss: 3.6631 - accuracy: 0.5017 - val_loss: 3.6885 - val_accuracy: 0.4055
Epoch 2/150
19/19 [==============================] - 0s 5ms/step - loss: 2.5882 - accuracy: 0.4267 - val_loss: 2.6277 - val_accuracy: 0.3849
Epoch 3/150
19/19 [==============================] - 0s 4ms/step - loss: 1.7694 - accuracy: 0.4133 - val_loss: 1.4561 - val_accuracy: 0.3918
Epoch 4/150
19/19 [==============================] - 0s 4ms/step - loss: 1.0078 - accuracy: 0.4617 - val_loss: 0.7689 - val_accuracy: 0.5567
Epoch 5/150
19/19 [==============================] - 0s 4ms/step - loss: 0.7749 - accuracy: 0.5933 - val_loss: 0.6442 - val_accuracy: 0.6460
Epoch 6/150
19/19 [==============================] - 0s 4ms/step - loss: 0.7388 - accuracy: 0.6150 - val_loss: 0.6159 - val_accuracy: 0.6632
Epoch 7/150
19/19 [==============================] - 0s 4ms/step - loss: 0.7154 - accuracy: 0.6133 - val_loss: 0.6037 - val_accuracy: 0.6667
Epoch 8/150
19/19 [==============================] - 0s 4ms/step - loss: 0.6959 - accuracy: 0.6200 - val_loss: 0.5880 - val_accuracy: 0.6873
Epoch 9/150
19/19 [==============================] - 0s 4ms/step - loss: 0.6758 - accuracy: 0.6433 - val_loss: 0.5761 - val_accuracy: 0.7010
Epoch 10/150
19/19 [==============================] - 0s 4ms/step - loss: 0.6580 - accuracy: 0.6617 - val_loss: 0.5681 - val_accuracy: 0.7113
Epoch 11/150
19/19 [==============================] - 0s 3ms/step - loss: 0.6412 - accuracy: 0.6583 - val_loss: 0.5615 - val_accuracy: 0.7148
Epoch 12/150
19/19 [==============================] - 0s 4ms/step - loss: 0.6313 - accuracy: 0.6550 - val_loss: 0.5463 - val_accuracy: 0.7216
Epoch 13/150
19/19 [==============================] - 0s 3ms/step - loss: 0.6184 - accuracy: 0.6783 - val_loss: 0.5363 - val_accuracy: 0.7251
Epoch 14/150
19/19 [==============================] - 0s 3ms/step - loss: 0.6084 - accuracy: 0.6750 - val_loss: 0.5359 - val_accuracy: 0.7320
Epoch 15/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5957 - accuracy: 0.6800 - val_loss: 0.5352 - val_accuracy: 0.7182
Epoch 16/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5873 - accuracy: 0.6833 - val_loss: 0.5243 - val_accuracy: 0.7457
Epoch 17/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5799 - accuracy: 0.6983 - val_loss: 0.5189 - val_accuracy: 0.7491
Epoch 18/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5756 - accuracy: 0.6900 - val_loss: 0.5123 - val_accuracy: 0.7526
Epoch 19/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5697 - accuracy: 0.6967 - val_loss: 0.5188 - val_accuracy: 0.7423
Epoch 20/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5676 - accuracy: 0.7067 - val_loss: 0.5042 - val_accuracy: 0.7595
Epoch 21/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5589 - accuracy: 0.7217 - val_loss: 0.5096 - val_accuracy: 0.7491
Epoch 22/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5569 - accuracy: 0.7067 - val_loss: 0.5051 - val_accuracy: 0.7457
Epoch 23/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5573 - accuracy: 0.7167 - val_loss: 0.4957 - val_accuracy: 0.7629
Epoch 24/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5514 - accuracy: 0.7183 - val_loss: 0.4979 - val_accuracy: 0.7526
Epoch 25/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5440 - accuracy: 0.7267 - val_loss: 0.4970 - val_accuracy: 0.7629
Epoch 26/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5434 - accuracy: 0.7300 - val_loss: 0.4975 - val_accuracy: 0.7560
Epoch 27/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5367 - accuracy: 0.7317 - val_loss: 0.4865 - val_accuracy: 0.7663
Epoch 28/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5357 - accuracy: 0.7350 - val_loss: 0.4896 - val_accuracy: 0.7629
Epoch 29/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5390 - accuracy: 0.7217 - val_loss: 0.4925 - val_accuracy: 0.7560
Epoch 30/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5321 - accuracy: 0.7417 - val_loss: 0.4834 - val_accuracy: 0.7766
Epoch 31/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5287 - accuracy: 0.7367 - val_loss: 0.4814 - val_accuracy: 0.7560
Epoch 32/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5240 - accuracy: 0.7483 - val_loss: 0.4801 - val_accuracy: 0.7801
Epoch 33/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5243 - accuracy: 0.7500 - val_loss: 0.4825 - val_accuracy: 0.7732
Epoch 34/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5246 - accuracy: 0.7483 - val_loss: 0.4794 - val_accuracy: 0.7560
Epoch 35/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5195 - accuracy: 0.7767 - val_loss: 0.4765 - val_accuracy: 0.7766
Epoch 36/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5182 - accuracy: 0.7767 - val_loss: 0.4730 - val_accuracy: 0.8007
Epoch 37/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5224 - accuracy: 0.7583 - val_loss: 0.4723 - val_accuracy: 0.7835
Epoch 38/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5128 - accuracy: 0.7683 - val_loss: 0.4660 - val_accuracy: 0.7560
Epoch 39/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5098 - accuracy: 0.7567 - val_loss: 0.4668 - val_accuracy: 0.7835
Epoch 40/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5094 - accuracy: 0.7817 - val_loss: 0.4751 - val_accuracy: 0.7732
Epoch 41/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5099 - accuracy: 0.7600 - val_loss: 0.4717 - val_accuracy: 0.7938
Epoch 42/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5142 - accuracy: 0.7717 - val_loss: 0.4610 - val_accuracy: 0.7732
Epoch 43/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5056 - accuracy: 0.7717 - val_loss: 0.4647 - val_accuracy: 0.7801
Epoch 44/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5046 - accuracy: 0.7833 - val_loss: 0.4642 - val_accuracy: 0.7869
Epoch 45/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5012 - accuracy: 0.7850 - val_loss: 0.4627 - val_accuracy: 0.7801
Epoch 46/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5054 - accuracy: 0.7700 - val_loss: 0.4699 - val_accuracy: 0.7835
Epoch 47/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4952 - accuracy: 0.7883 - val_loss: 0.4605 - val_accuracy: 0.7938
Epoch 48/150
19/19 [==============================] - 0s 3ms/step - loss: 0.5026 - accuracy: 0.7783 - val_loss: 0.4610 - val_accuracy: 0.7904
Epoch 49/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4997 - accuracy: 0.7750 - val_loss: 0.4688 - val_accuracy: 0.7835
Epoch 50/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4968 - accuracy: 0.7883 - val_loss: 0.4590 - val_accuracy: 0.7938
Epoch 51/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4963 - accuracy: 0.7950 - val_loss: 0.4516 - val_accuracy: 0.7973
Epoch 52/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4942 - accuracy: 0.7767 - val_loss: 0.4622 - val_accuracy: 0.7835
Epoch 53/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4969 - accuracy: 0.7833 - val_loss: 0.4564 - val_accuracy: 0.7904
Epoch 54/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4987 - accuracy: 0.7900 - val_loss: 0.4597 - val_accuracy: 0.7904
Epoch 55/150
19/19 [==============================] - 0s 4ms/step - loss: 0.5044 - accuracy: 0.7600 - val_loss: 0.4581 - val_accuracy: 0.7835
Epoch 56/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4931 - accuracy: 0.7817 - val_loss: 0.4640 - val_accuracy: 0.7869
Epoch 57/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4913 - accuracy: 0.7833 - val_loss: 0.4496 - val_accuracy: 0.7904
Epoch 58/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4901 - accuracy: 0.7733 - val_loss: 0.4519 - val_accuracy: 0.7938

Epoch 59/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4873 - accuracy: 0.7783 - val_loss: 0.4619 - val_accuracy: 0.7973
Epoch 60/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4892 - accuracy: 0.7850 - val_loss: 0.4472 - val_accuracy: 0.7904
Epoch 61/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4944 - accuracy: 0.7600 - val_loss: 0.4613 - val_accuracy: 0.7938
Epoch 62/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4902 - accuracy: 0.7867 - val_loss: 0.4471 - val_accuracy: 0.7835
Epoch 63/150
19/19 [==============================] - 0s 5ms/step - loss: 0.4844 - accuracy: 0.7833 - val_loss: 0.4521 - val_accuracy: 0.7973
Epoch 64/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4834 - accuracy: 0.7767 - val_loss: 0.4495 - val_accuracy: 0.7938
Epoch 65/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4832 - accuracy: 0.7833 - val_loss: 0.4474 - val_accuracy: 0.7835
Epoch 66/150
19/19 [==============================] - 0s 5ms/step - loss: 0.4896 - accuracy: 0.7717 - val_loss: 0.4605 - val_accuracy: 0.7904
Epoch 67/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4869 - accuracy: 0.7750 - val_loss: 0.4468 - val_accuracy: 0.7938
Epoch 68/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4846 - accuracy: 0.7867 - val_loss: 0.4476 - val_accuracy: 0.7904
Epoch 69/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4845 - accuracy: 0.7883 - val_loss: 0.4493 - val_accuracy: 0.7938
Epoch 70/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4815 - accuracy: 0.7783 - val_loss: 0.4482 - val_accuracy: 0.7973
Epoch 71/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4836 - accuracy: 0.7800 - val_loss: 0.4406 - val_accuracy: 0.7869
Epoch 72/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4817 - accuracy: 0.7817 - val_loss: 0.4523 - val_accuracy: 0.7973
Epoch 73/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4794 - accuracy: 0.7800 - val_loss: 0.4485 - val_accuracy: 0.7973
Epoch 74/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4822 - accuracy: 0.7883 - val_loss: 0.4443 - val_accuracy: 0.7904
Epoch 75/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4880 - accuracy: 0.7767 - val_loss: 0.4521 - val_accuracy: 0.7973
Epoch 76/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4816 - accuracy: 0.7850 - val_loss: 0.4548 - val_accuracy: 0.7938
Epoch 77/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4811 - accuracy: 0.7867 - val_loss: 0.4395 - val_accuracy: 0.7904
Epoch 78/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4795 - accuracy: 0.7850 - val_loss: 0.4488 - val_accuracy: 0.7869
Epoch 79/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4790 - accuracy: 0.7817 - val_loss: 0.4451 - val_accuracy: 0.7938
Epoch 80/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4787 - accuracy: 0.7867 - val_loss: 0.4415 - val_accuracy: 0.7835
Epoch 81/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4789 - accuracy: 0.7783 - val_loss: 0.4468 - val_accuracy: 0.7973
Epoch 82/150
19/19 [==============================] - 0s 5ms/step - loss: 0.4845 - accuracy: 0.7783 - val_loss: 0.4667 - val_accuracy: 0.7869
Epoch 83/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4814 - accuracy: 0.7800 - val_loss: 0.4433 - val_accuracy: 0.7801
Epoch 84/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4778 - accuracy: 0.7917 - val_loss: 0.4465 - val_accuracy: 0.7973
Epoch 85/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4813 - accuracy: 0.7883 - val_loss: 0.4583 - val_accuracy: 0.7904
Epoch 86/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4789 - accuracy: 0.7867 - val_loss: 0.4391 - val_accuracy: 0.7938
Epoch 87/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4763 - accuracy: 0.7783 - val_loss: 0.4614 - val_accuracy: 0.7938
Epoch 88/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4756 - accuracy: 0.7883 - val_loss: 0.4379 - val_accuracy: 0.7869
Epoch 89/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4777 - accuracy: 0.7783 - val_loss: 0.4394 - val_accuracy: 0.7904
Epoch 90/150
19/19 [==============================] - 0s 5ms/step - loss: 0.4760 - accuracy: 0.7783 - val_loss: 0.4626 - val_accuracy: 0.7904
Epoch 91/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4823 - accuracy: 0.7767 - val_loss: 0.4342 - val_accuracy: 0.7869
Epoch 92/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4757 - accuracy: 0.7850 - val_loss: 0.4415 - val_accuracy: 0.7904
Epoch 93/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4752 - accuracy: 0.7833 - val_loss: 0.4496 - val_accuracy: 0.7938
Epoch 94/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4783 - accuracy: 0.7917 - val_loss: 0.4440 - val_accuracy: 0.7973
Epoch 95/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4838 - accuracy: 0.7767 - val_loss: 0.4647 - val_accuracy: 0.7904
Epoch 96/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4752 - accuracy: 0.7850 - val_loss: 0.4383 - val_accuracy: 0.7938
Epoch 97/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4781 - accuracy: 0.7833 - val_loss: 0.4465 - val_accuracy: 0.7869
Epoch 98/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4755 - accuracy: 0.7767 - val_loss: 0.4477 - val_accuracy: 0.7938
Epoch 99/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4736 - accuracy: 0.7933 - val_loss: 0.4381 - val_accuracy: 0.7938
Epoch 100/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4732 - accuracy: 0.7867 - val_loss: 0.4380 - val_accuracy: 0.7938
Epoch 101/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4751 - accuracy: 0.7817 - val_loss: 0.4487 - val_accuracy: 0.7904
Epoch 102/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4749 - accuracy: 0.7867 - val_loss: 0.4398 - val_accuracy: 0.7904
Epoch 103/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4769 - accuracy: 0.7700 - val_loss: 0.4374 - val_accuracy: 0.7904
Epoch 104/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4740 - accuracy: 0.7867 - val_loss: 0.4387 - val_accuracy: 0.7938
Epoch 105/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4753 - accuracy: 0.7833 - val_loss: 0.4420 - val_accuracy: 0.7938
Epoch 106/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4778 - accuracy: 0.7850 - val_loss: 0.4403 - val_accuracy: 0.7938
Epoch 107/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4738 - accuracy: 0.7817 - val_loss: 0.4323 - val_accuracy: 0.7904
Epoch 108/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4738 - accuracy: 0.7883 - val_loss: 0.4370 - val_accuracy: 0.7904
Epoch 109/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4714 - accuracy: 0.7850 - val_loss: 0.4349 - val_accuracy: 0.7938
Epoch 110/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4720 - accuracy: 0.7817 - val_loss: 0.4399 - val_accuracy: 0.7973
Epoch 111/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4748 - accuracy: 0.7900 - val_loss: 0.4336 - val_accuracy: 0.7904
Epoch 112/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4730 - accuracy: 0.7883 - val_loss: 0.4477 - val_accuracy: 0.7904
Epoch 113/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4708 - accuracy: 0.7817 - val_loss: 0.4338 - val_accuracy: 0.7904
Epoch 114/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4711 - accuracy: 0.7817 - val_loss: 0.4341 - val_accuracy: 0.7904
Epoch 115/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4712 - accuracy: 0.7917 - val_loss: 0.4376 - val_accuracy: 0.7904
Epoch 116/150

19/19 [==============================] - 0s 4ms/step - loss: 0.4698 - accuracy: 0.7800 - val_loss: 0.4342 - val_accuracy: 0.7904
Epoch 117/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4704 - accuracy: 0.7950 - val_loss: 0.4330 - val_accuracy: 0.7766
Epoch 118/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4728 - accuracy: 0.7750 - val_loss: 0.4512 - val_accuracy: 0.7904
Epoch 119/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4742 - accuracy: 0.7900 - val_loss: 0.4343 - val_accuracy: 0.7869
Epoch 120/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4729 - accuracy: 0.7900 - val_loss: 0.4305 - val_accuracy: 0.7938
Epoch 121/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4697 - accuracy: 0.7850 - val_loss: 0.4353 - val_accuracy: 0.7835
Epoch 122/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4710 - accuracy: 0.7817 - val_loss: 0.4365 - val_accuracy: 0.7904
Epoch 123/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4715 - accuracy: 0.7850 - val_loss: 0.4357 - val_accuracy: 0.7904
Epoch 124/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4685 - accuracy: 0.7883 - val_loss: 0.4312 - val_accuracy: 0.7938
Epoch 125/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4709 - accuracy: 0.7867 - val_loss: 0.4530 - val_accuracy: 0.7904
Epoch 126/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4750 - accuracy: 0.7900 - val_loss: 0.4272 - val_accuracy: 0.7973
Epoch 127/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4709 - accuracy: 0.7817 - val_loss: 0.4471 - val_accuracy: 0.7904
Epoch 128/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4820 - accuracy: 0.7833 - val_loss: 0.4731 - val_accuracy: 0.7869
Epoch 129/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4677 - accuracy: 0.7800 - val_loss: 0.4311 - val_accuracy: 0.7801
Epoch 130/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4714 - accuracy: 0.7867 - val_loss: 0.4346 - val_accuracy: 0.7904
Epoch 131/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4695 - accuracy: 0.7900 - val_loss: 0.4307 - val_accuracy: 0.7904
Epoch 132/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4692 - accuracy: 0.7867 - val_loss: 0.4277 - val_accuracy: 0.7938
Epoch 133/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4725 - accuracy: 0.7900 - val_loss: 0.4347 - val_accuracy: 0.7766
Epoch 134/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4683 - accuracy: 0.7783 - val_loss: 0.4395 - val_accuracy: 0.7938
Epoch 135/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4715 - accuracy: 0.7833 - val_loss: 0.4324 - val_accuracy: 0.8007
Epoch 136/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4697 - accuracy: 0.7900 - val_loss: 0.4348 - val_accuracy: 0.7973
Epoch 137/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4696 - accuracy: 0.7883 - val_loss: 0.4396 - val_accuracy: 0.7904
Epoch 138/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4703 - accuracy: 0.7900 - val_loss: 0.4293 - val_accuracy: 0.7801
Epoch 139/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4762 - accuracy: 0.7883 - val_loss: 0.4311 - val_accuracy: 0.7904
Epoch 140/150
19/19 [==============================] - 0s 3ms/step - loss: 0.4712 - accuracy: 0.7967 - val_loss: 0.4323 - val_accuracy: 0.7938
Epoch 141/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4694 - accuracy: 0.7917 - val_loss: 0.4366 - val_accuracy: 0.7973
Epoch 142/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4663 - accuracy: 0.7950 - val_loss: 0.4284 - val_accuracy: 0.7835
Epoch 143/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4692 - accuracy: 0.7817 - val_loss: 0.4318 - val_accuracy: 0.7938
Epoch 144/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4696 - accuracy: 0.7883 - val_loss: 0.4302 - val_accuracy: 0.7801
Epoch 145/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4729 - accuracy: 0.7917 - val_loss: 0.4305 - val_accuracy: 0.7938
Epoch 146/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4722 - accuracy: 0.7817 - val_loss: 0.4380 - val_accuracy: 0.7904
Epoch 147/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4685 - accuracy: 0.7950 - val_loss: 0.4279 - val_accuracy: 0.7869
Epoch 148/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4675 - accuracy: 0.7767 - val_loss: 0.4511 - val_accuracy: 0.7938
Epoch 149/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4685 - accuracy: 0.7917 - val_loss: 0.4306 - val_accuracy: 0.7904
Epoch 150/150
19/19 [==============================] - 0s 4ms/step - loss: 0.4705 - accuracy: 0.7900 - val_loss: 0.4291 - val_accuracy: 0.7904

# Saving Predictions For Submission

In [13]:
pred = model.predict(testX)

14/14 [==============================] - 0s 1ms/step

In [14]:
pred = [1 if (prediction >= 0.5) else 0  for prediction in pred]

In [15]:
df = pd.DataFrame({"PassengerId":testData['PassengerId'], "Survived":pred})

In [16]:
df.to_csv("submission.csv", index = False)